print("Addition of  Two numbers")
a=int(input("Enter 1st number:"))
b=int(input("Enter 2nd number:"))
print("Addition of ",a," and ",b," is :",a+b)
print("Successfull!!")
print("Adding lines through GitHub Account...!!!")
print("hi")
